/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.8.34
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ProjectProjectIdTasksGetRequest struct for ProjectProjectIdTasksGetRequest
type ProjectProjectIdTasksGetRequest struct {
	TemplateId *int32 `json:"template_id,omitempty"`
	Debug *bool `json:"debug,omitempty"`
	DryRun *bool `json:"dry_run,omitempty"`
	Playbook *string `json:"playbook,omitempty"`
	Environment *string `json:"environment,omitempty"`
}

// NewProjectProjectIdTasksGetRequest instantiates a new ProjectProjectIdTasksGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectProjectIdTasksGetRequest() *ProjectProjectIdTasksGetRequest {
	this := ProjectProjectIdTasksGetRequest{}
	return &this
}

// NewProjectProjectIdTasksGetRequestWithDefaults instantiates a new ProjectProjectIdTasksGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectProjectIdTasksGetRequestWithDefaults() *ProjectProjectIdTasksGetRequest {
	this := ProjectProjectIdTasksGetRequest{}
	return &this
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *ProjectProjectIdTasksGetRequest) GetTemplateId() int32 {
	if o == nil || o.TemplateId == nil {
		var ret int32
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProjectIdTasksGetRequest) GetTemplateIdOk() (*int32, bool) {
	if o == nil || o.TemplateId == nil {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *ProjectProjectIdTasksGetRequest) HasTemplateId() bool {
	if o != nil && o.TemplateId != nil {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given int32 and assigns it to the TemplateId field.
func (o *ProjectProjectIdTasksGetRequest) SetTemplateId(v int32) {
	o.TemplateId = &v
}

// GetDebug returns the Debug field value if set, zero value otherwise.
func (o *ProjectProjectIdTasksGetRequest) GetDebug() bool {
	if o == nil || o.Debug == nil {
		var ret bool
		return ret
	}
	return *o.Debug
}

// GetDebugOk returns a tuple with the Debug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProjectIdTasksGetRequest) GetDebugOk() (*bool, bool) {
	if o == nil || o.Debug == nil {
		return nil, false
	}
	return o.Debug, true
}

// HasDebug returns a boolean if a field has been set.
func (o *ProjectProjectIdTasksGetRequest) HasDebug() bool {
	if o != nil && o.Debug != nil {
		return true
	}

	return false
}

// SetDebug gets a reference to the given bool and assigns it to the Debug field.
func (o *ProjectProjectIdTasksGetRequest) SetDebug(v bool) {
	o.Debug = &v
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *ProjectProjectIdTasksGetRequest) GetDryRun() bool {
	if o == nil || o.DryRun == nil {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProjectIdTasksGetRequest) GetDryRunOk() (*bool, bool) {
	if o == nil || o.DryRun == nil {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *ProjectProjectIdTasksGetRequest) HasDryRun() bool {
	if o != nil && o.DryRun != nil {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *ProjectProjectIdTasksGetRequest) SetDryRun(v bool) {
	o.DryRun = &v
}

// GetPlaybook returns the Playbook field value if set, zero value otherwise.
func (o *ProjectProjectIdTasksGetRequest) GetPlaybook() string {
	if o == nil || o.Playbook == nil {
		var ret string
		return ret
	}
	return *o.Playbook
}

// GetPlaybookOk returns a tuple with the Playbook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProjectIdTasksGetRequest) GetPlaybookOk() (*string, bool) {
	if o == nil || o.Playbook == nil {
		return nil, false
	}
	return o.Playbook, true
}

// HasPlaybook returns a boolean if a field has been set.
func (o *ProjectProjectIdTasksGetRequest) HasPlaybook() bool {
	if o != nil && o.Playbook != nil {
		return true
	}

	return false
}

// SetPlaybook gets a reference to the given string and assigns it to the Playbook field.
func (o *ProjectProjectIdTasksGetRequest) SetPlaybook(v string) {
	o.Playbook = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *ProjectProjectIdTasksGetRequest) GetEnvironment() string {
	if o == nil || o.Environment == nil {
		var ret string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProjectIdTasksGetRequest) GetEnvironmentOk() (*string, bool) {
	if o == nil || o.Environment == nil {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *ProjectProjectIdTasksGetRequest) HasEnvironment() bool {
	if o != nil && o.Environment != nil {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given string and assigns it to the Environment field.
func (o *ProjectProjectIdTasksGetRequest) SetEnvironment(v string) {
	o.Environment = &v
}

func (o ProjectProjectIdTasksGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TemplateId != nil {
		toSerialize["template_id"] = o.TemplateId
	}
	if o.Debug != nil {
		toSerialize["debug"] = o.Debug
	}
	if o.DryRun != nil {
		toSerialize["dry_run"] = o.DryRun
	}
	if o.Playbook != nil {
		toSerialize["playbook"] = o.Playbook
	}
	if o.Environment != nil {
		toSerialize["environment"] = o.Environment
	}
	return json.Marshal(toSerialize)
}

type NullableProjectProjectIdTasksGetRequest struct {
	value *ProjectProjectIdTasksGetRequest
	isSet bool
}

func (v NullableProjectProjectIdTasksGetRequest) Get() *ProjectProjectIdTasksGetRequest {
	return v.value
}

func (v *NullableProjectProjectIdTasksGetRequest) Set(val *ProjectProjectIdTasksGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectProjectIdTasksGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectProjectIdTasksGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectProjectIdTasksGetRequest(val *ProjectProjectIdTasksGetRequest) *NullableProjectProjectIdTasksGetRequest {
	return &NullableProjectProjectIdTasksGetRequest{value: val, isSet: true}
}

func (v NullableProjectProjectIdTasksGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectProjectIdTasksGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


