=begin
#API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.8.34

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AuthenticationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuthenticationApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AuthenticationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthenticationApi' do
    it 'should create an instance of AuthenticationApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AuthenticationApi)
    end
  end

  # unit tests for auth_login_post
  # Performs Login
  # Upon success you will be logged in
  # @param login_body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'auth_login_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for auth_logout_post
  # Destroys current session
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'auth_logout_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for user_tokens_api_token_id_delete
  # Expires API token
  # @param api_token_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'user_tokens_api_token_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for user_tokens_get
  # Fetch API tokens for user
  # @param [Hash] opts the optional parameters
  # @return [Array<APIToken>]
  describe 'user_tokens_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for user_tokens_post
  # Create an API token
  # @param [Hash] opts the optional parameters
  # @return [APIToken]
  describe 'user_tokens_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
