=begin
#API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.8.34

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ScheduleApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ScheduleApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ScheduleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScheduleApi' do
    it 'should create an instance of ScheduleApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ScheduleApi)
    end
  end

  # unit tests for project_project_id_schedules_post
  # create schedule
  # @param project_id Project ID
  # @param schedule 
  # @param [Hash] opts the optional parameters
  # @return [Schedule]
  describe 'project_project_id_schedules_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_project_id_schedules_schedule_id_delete
  # Deletes schedule
  # @param project_id Project ID
  # @param schedule_id schedule ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'project_project_id_schedules_schedule_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_project_id_schedules_schedule_id_get
  # Get schedule
  # @param project_id Project ID
  # @param schedule_id schedule ID
  # @param [Hash] opts the optional parameters
  # @return [Schedule]
  describe 'project_project_id_schedules_schedule_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_project_id_schedules_schedule_id_put
  # Updates schedule
  # @param project_id Project ID
  # @param schedule_id schedule ID
  # @param schedule 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'project_project_id_schedules_schedule_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
